### ISSUE TITLE
i  can't find the excel after i run this program succsefully?

### ISSUE THREAD

**Issue by tang123456654321** [WebberCao/Ocr2Excel#1]
can you help me ?my email is 1907103274@qq.com.I reallly nead your help.plaese contact me.thank you very much.

**Comment by WebberCao** [comment]
OK, let me see, I will reply to you today or tomorrow.

**Comment by tang123456654321** [comment]
thank you very much.And looking forward your reply.

**Comment by WebberCao** [comment]
I have fixed the file path problem，you can download the latest code and try it. Thank you very much for your question.

**Comment by tang123456654321** [comment]
OK，thanks。i will try it again tonight.

**Comment by tang123456654321** [comment]
So now the code on the platform is the latest version?

**Comment by tang123456654321** [comment]
I have successfully run the program and found the file. But is this program only for neat and simple images? When I try to run a slightly more complex image, the recognition doesn't work very well. And sometimes there is nothing in the table after i run this program successfully. Could you give me some answers?thank you very much.

**Comment by tang123456654321** [comment]
Does the recognition program require table styles?

**Comment by tang123456654321** [comment]
I've just identified four boxes of images taken from the excel document, and only one of them is correct. So I'm wondering is this a requirement for font eye style and table style for content?

**Comment by WebberCao** [comment]
For table identification, this is actually only a preliminary version, so there are certain requirements for the identified form image. It is better to increase the brightness and contrast of the picture after taking the picture, which will improve the recognition success rate.

**Comment by tang123456654321** [comment]
Could you show me the source code of C + + please? I want to know what's inside the code and to make changes. Thank you very much.

**Comment by WebberCao** [comment]
OK , I will upload the source code of C++ later .

**Comment by tang123456654321** [comment]
thank you very much!

**Comment by tang123456654321** [comment]
Excuse me, where can I find C++ source code ah? I tried to find it but failed.

**Comment by WebberCao** [comment]
Sorry, there are so many things lately. I haven't had time to upload them. I'll upload them later.

**Comment by WebberCao** [comment]
I have uploaded the code，you can find them in "Ocr2Excel/app/src/main/assets/ImageProcessor/"，If you find it, please close the issuse.
